version: '3.8'

services:
  blog:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount blueprint file
      - ./blueprint.toml:/app/blueprint.toml:ro
      # Mount data directory for SQLite persistence
      - blog-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=sqlite:///app/data/app.db
      - BLUEPRINT_PATH=/app/blueprint.toml
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    restart: unless-stopped

volumes:
  blog-data:
    driver: local
