#!/usr/bin/env node
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs/promises'
import postcss from 'postcss'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')

const inputPath = path.join(rootDir, 'src/renderer/styles/tailwind.css')
const outputCssPath = path.join(rootDir, 'src/renderer/styles/tailwind.generated.css')
const outputTsPath = path.join(rootDir, 'src/renderer/styles/tailwind.generated.ts')
const tailwindConfigPath = path.join(rootDir, 'tailwind.config.cjs')

async function build() {
  const css = await fs.readFile(inputPath, 'utf8')
  const processor = postcss([
    tailwindcss({
      config: tailwindConfigPath
    }),
    autoprefixer()
  ])

  const result = await processor.process(css, {
    from: inputPath,
    to: outputCssPath
  })

  await fs.mkdir(path.dirname(outputCssPath), { recursive: true })
  await fs.writeFile(outputCssPath, result.css, 'utf8')

  const banner = `// This file is generated by scripts/build-css.mjs\nexport const BUILT_TAILWIND_CSS = ${JSON.stringify(result.css)};\n`
  await fs.writeFile(outputTsPath, banner, 'utf8')

  console.log(`[tailwind] CSS built -> ${path.relative(rootDir, outputTsPath)}`)
}

build().catch(error => {
  console.error('[tailwind] Failed to build CSS:', error)
  process.exitCode = 1
})
