#!/usr/bin/env node
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs/promises'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

const pkg = JSON.parse(await fs.readFile(path.join(rootDir, 'package.json'), 'utf8'))
const outputPath = path.join(rootDir, 'src/version.generated.ts')

const banner = `// This file is generated by scripts/build-version.mjs\nexport const ZEBRIC_VERSION = ${JSON.stringify(pkg.version)};\n`
await fs.writeFile(outputPath, banner, 'utf8')

console.log(`[version] ${pkg.version} -> ${path.relative(rootDir, outputPath)}`)
